### PR TITLE
Net 217 update config

### PR DESCRIPTION
**Pull request by isentropy**
- update addresses and default RPC
- add sendToMainnet boolean arg
- more reasonable gas limit
- update DU contract wrappers

### CODE REVIEW

**Review by jtakalai — CHANGES_REQUESTED** [review]
code looks good but following tests fail:
```
com.streamr.client.DataUnionClientSpec > create DU FAILED
    groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.streamr.client.dataunion.EstimatedGasProvider(org.web3j.protocol.core.JsonRpc2_0Web3j)
        at com.streamr.client.DataUnionClientSpec.setup(DataUnionClientSpec.groovy:45)
com.streamr.client.DataUnionClientSpec > add members FAILED
    groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.streamr.client.dataunion.EstimatedGasProvider(org.web3j.protocol.core.JsonRpc2_0Web3j)
        at com.streamr.client.DataUnionClientSpec.setup(DataUnionClientSpec.groovy:45)
com.streamr.client.DataUnionClientSpec > test transfer and sidechain stats FAILED
    groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.streamr.client.dataunion.EstimatedGasProvider(org.web3j.protocol.core.JsonRpc2_0Web3j)
        at com.streamr.client.DataUnionClientSpec.setup(DataUnionClientSpec.groovy:45)
com.streamr.client.DataUnionClientSpec > withdraw member as admin FAILED
    groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.streamr.client.dataunion.EstimatedGasProvider(org.web3j.protocol.core.JsonRpc2_0Web3j)
        at com.streamr.client.DataUnionClientSpec.setup(DataUnionClientSpec.groovy:45)
com.streamr.client.DataUnionClientSpec > signed withdrawal for another FAILED
    groovy.lang.GroovyRuntimeException: Could not find matching constructor for: com.streamr.client.dataunion.EstimatedGasProvider(org.web3j.protocol.core.JsonRpc2_0Web3j)
        at com.streamr.client.DataUnionClientSpec.setup(DataUnionClientSpec.groovy:45)
```

Should they be disabled or fixed?

**Review by samt1803 — COMMENTED** [review]
apart from the ci build not working code changes look fine to me

**Comment by kare** [comment]
Some of the test fixes are on `release/v3.0.0` branch. Production code is essentially the same.

**Review by jtakalai — APPROVED** [review]
the test errors are gone

**Pull request merged**
